### ISSUE TITLE
Doesn't detect plugins

### ISSUE THREAD

**Issue by thereln** [weespin/RequestifyTF2#44]
It doesn't seem to detect plugins in the "plugins" folder even though there are plugins. Not sure if anyone else has this problem.
[Error][29/07/2019 19:08:44] System.NullReferenceException: Object reference not set to an instance of an object.
   at RequestifyTF2.PluginLoader.Libraries.Load(String path) in C:\projects\requestifytf2\src\Core\RequestifyTF2\PluginLoader\Libraries.cs:line 22
[Error][29/07/2019 19:08:44] System.NullReferenceException: Object reference not set to an instance of an object.
   at RequestifyTF2.PluginLoader.Libraries.Load(String path) in C:\projects\requestifytf2\src\Core\RequestifyTF2\PluginLoader\Libraries.cs:line 22
[Error][29/07/2019 19:08:44] System.NullReferenceException: Object reference not set to an instance of an object.
   at RequestifyTF2.PluginLoader.Libraries.Load(String path) in C:\projects\requestifytf2\src\Core\RequestifyTF2\PluginLoader\Libraries.cs:line 22
[Error][29/07/2019 19:08:44] System.NullReferenceException: Object reference not set to an instance of an object.
   at RequestifyTF2.PluginLoader.Libraries.Load(String path) in C:\projects\requestifytf2\src\Core\RequestifyTF2\PluginLoader\Libraries.cs:line 22
[Error][29/07/2019 19:08:45] I can't find any plugins

**Comment by AutismGaming228** [comment]
Can confirm, happens to me as well.
Windows 10 1903 build, requestify logs are exactly the same.

**Comment by weespin** [comment]
Just unblock dll's in plugins folder
e.g.
![image](https://user-images.githubusercontent.com/17180451/62977843-83c1db80-be28-11e9-9c1c-7f25e899c60b.png)
