### ISSUE TITLE
YouTube playlist response broken for 3+ days. TTS does nothing as well but shows command executed in log.

### ISSUE THREAD

**Issue by AlexWalker2** [weespin/RequestifyTF2#50]
[Error][9/14/2020 3:13:40 AM] YoutubeExplode.Exceptions.TransientFailureException: Playlist response is broken.
In most cases, this error indicates that the problem is on YouTube's side and this is not a bug in the library.
To resolve this error, please wait some time and try again.
If this issue persists, please report it on the project's GitHub page.
   at YoutubeExplode.ReverseEngineering.Responses.PlaylistResponse.Parse(String raw)
   at YoutubeExplode.ReverseEngineering.Responses.PlaylistResponse.<>c__DisplayClass12_0.<<GetSearchResultsAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.Internal.Retry.<WrapAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at YoutubeExplode.Internal.Retry.<WrapAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.ReverseEngineering.Responses.PlaylistResponse.<GetSearchResultsAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.Search.SearchClient.<GetVideosAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetResult(Int16 token)
   at YoutubeExplode.Search.SearchClient.<GetVideosAsync>d__2.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
   at YoutubeExplode.Internal.Extensions.AsyncEnumerableExtensions.<TakeAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at YoutubeExplode.Internal.Extensions.AsyncEnumerableExtensions.<TakeAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetResult(Int16 token)
   at YoutubeExplode.Internal.Extensions.AsyncEnumerableExtensions.<TakeAsync>d__0`1.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
   at YoutubeExplode.Internal.Extensions.AsyncEnumerableExtensions.<ToListAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at YoutubeExplode.Internal.Extensions.AsyncEnumerableExtensions.<ToListAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.AccessibilityExtensions.<BufferAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.AccessibilityExtensions.<BufferAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at RequestPlugin.VoteCommand.RequestCommand.Execute(User executor, List`1 arguments)
   at RequestifyTF2.Commands.Executer.<>c__DisplayClass0_0.<Execute>b__0() in C:\projects\requestifytf2\src\Core\RequestifyTF2\Commands\Executer.cs:line 80

**Comment by weespin** [comment]
fixed in 9f03ca5f442298acb1b258728ee65306c131fc30
