### ISSUE TITLE
Request function doesn't work, tts and everything else works fine.

### ISSUE THREAD

**Issue by MasterTarcus** [weespin/RequestifyTF2#51]
The request function does not work and returns this error in the log: 

System.AggregateException: One or more errors occurred. ---> System.Text.Json.JsonReaderException: 'a' is an invalid start of a property name. Expected a '"'. LineNumber: 0 | BytePositionInLine: 1.
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, Utf8JsonReader reader, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedBytes)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 json, JsonDocumentOptions options)
   at System.Text.Json.JsonDocument.Parse(String json, JsonDocumentOptions options)
   at YoutubeExplode.Internal.Json.Parse(String source)
   at YoutubeExplode.Internal.Extensions.GenericExtensions.Pipe[TIn,TOut](TIn input, Func`2 transform)
   at YoutubeExplode.ReverseEngineering.Responses.WatchPage.TryGetPlayerConfig()
   at YoutubeExplode.Videos.Streams.StreamClient.<GetStreamContextFromWatchPageAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.Videos.Streams.StreamClient.<GetManifestAsync>d__6.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at RequestPlugin.VoteCommand.RequestCommand.Execute(User executor, List`1 arguments)
   at RequestifyTF2.Commands.Executer.<>c__DisplayClass0_0.<Execute>b__0() in C:\projects\requestifytf2\src\Core\RequestifyTF2\Commands\Executer.cs:line 80
---> (Inner Exception #0) System.Text.Json.JsonReaderException: 'a' is an invalid start of a property name. Expected a '"'. LineNumber: 0 | BytePositionInLine: 1.
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, Utf8JsonReader reader, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedBytes)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 json, JsonDocumentOptions options)
   at System.Text.Json.JsonDocument.Parse(String json, JsonDocumentOptions options)
   at YoutubeExplode.Internal.Json.Parse(String source)
   at YoutubeExplode.Internal.Extensions.GenericExtensions.Pipe[TIn,TOut](TIn input, Func`2 transform)
   at YoutubeExplode.ReverseEngineering.Responses.WatchPage.TryGetPlayerConfig()
   at YoutubeExplode.Videos.Streams.StreamClient.<GetStreamContextFromWatchPageAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.Videos.Streams.StreamClient.<GetManifestAsync>d__6.MoveNext()<---

I have tested it on both my laptop and desktop, so I don't think it has anything to do with any computer setting. Was able to get previous versions to work just fine, but now old versions return with errors suggesting that there's an error on YouTube's end, and is probably not a code bug, and to wait and try again, but this message keeps returning everytime I try and use the request command.

**Comment by weespin** [comment]
Fixed in https://github.com/weespin/RequestifyTF2/commit/186ea6bf8a673a16fb22077f0c10640abf846656
