### ISSUE TITLE
Request and Tts function not working, we await your support lord.

### ISSUE THREAD

**Issue by AlexWalker2** [weespin/RequestifyTF2#54]
[Error][5/29/2021 11:53:56 PM] YoutubeExplode.Exceptions.TransientFailureException: Playlist response is broken.
In most cases, this error indicates that the problem is on YouTube's side and this is not a bug in the library.
To resolve this error, please wait some time and try again.
If this issue persists, please report it on the project's GitHub page.
   at YoutubeExplode.ReverseEngineering.Responses.PlaylistResponse.Parse(String raw)
   at YoutubeExplode.ReverseEngineering.Responses.PlaylistResponse.<>c__DisplayClass13_0.<<GetSearchResultsAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.Internal.Retry.<WrapAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at YoutubeExplode.Internal.Retry.<WrapAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.ReverseEngineering.Responses.PlaylistResponse.<GetSearchResultsAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.Search.SearchClient.<GetVideosAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetResult(Int16 token)
   at YoutubeExplode.Search.SearchClient.<GetVideosAsync>d__2.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
   at YoutubeExplode.Internal.Extensions.AsyncEnumerableExtensions.<TakeAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at YoutubeExplode.Internal.Extensions.AsyncEnumerableExtensions.<TakeAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetResult(Int16 token)
   at YoutubeExplode.Internal.Extensions.AsyncEnumerableExtensions.<TakeAsync>d__0`1.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
   at YoutubeExplode.Internal.Extensions.AsyncEnumerableExtensions.<ToListAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at YoutubeExplode.Internal.Extensions.AsyncEnumerableExtensions.<ToListAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.AccessibilityExtensions.<BufferAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.AccessibilityExtensions.<BufferAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at RequestPlugin.VoteCommand.RequestCommand.Execute(User executor, List`1 arguments)
   at RequestifyTF2.Commands.Executer.<>c__DisplayClass0_0.<Execute>b__0() in C:\projects\requestifytf2\src\Core\RequestifyTF2\Commands\Executer.cs:line 80
[Info][5/29/2021 11:54:30 PM] !request (link) !tts (prompt) executed !tts

**Comment by weespin** [comment]
Fixed in https://github.com/weespin/RequestifyTF2/commit/186ea6bf8a673a16fb22077f0c10640abf846656
